### PR TITLE
Added BFQ scheduler

### PR DESCRIPTION
**Pull request by CactusPie**
I've added BFQ as a non-default scheduler. I know you once refused to add it to the kernel on the forums, so if you reject the pull request, that's fine. Chances are nobody else besides me wants to use it.

### CODE REVIEW

**Comment by AndyLaiJS** [comment]
I actually want to know why you want BFQ lol. All I've been hearing about it is mostly bad things

**Comment by CactusPie** [comment]
It's supposed to be faster under heavy load and with multitasking - perfect for the internal storage. It should improve responsiveness of the system. From my recent tests it's been performing pretty well. Could you link me some sources that say it's not very good?

Here is one nice benchmark I found that tests it under heavy load, compared to Deadline. It's for HDD not SSD though, so I guess it might be a bit misleading...
http://www.hecticgeek.com/2012/11/bfq-loads-programs-extremely-fast-under-heavy-disk-io-workloads-ubuntu/

**Comment by AndyLaiJS** [comment]
https://github.com/sonyxperiadev/kernel/pull/642

**Comment by CactusPie** [comment]
This essentially confirms the comparison I've found:

Overall performance:
FIOPS > Noop > ZEN > Tripndroid > SIO > ROW > SIOplus > VR > Deadline > BFQ > CFQ

Multitasking performance:
Noop < FIFO < FIOPS < SIO <  SIOplus < ROW < Tripndroid < ZEN < Deadline < VR <  CFQ < BFQ

Battery life:
Noop > FIFO > FIOPS > SIO > SIOplus > ROW >  ZEN > Tripndroid > Deadline > VR > CFQ > BFQ

Well, it's up to you. I can always recompile the kernel with every new release to add this scheduler.

**Comment by AndyLaiJS** [comment]
The comparison you showed me shows that BFQ is terrible in "overall performance" and battery life but reign supreme in BFQ. I guess I'll add it in for the sake of multiple choices :)

Thanks though

**Comment by CactusPie** [comment]
Yup, that's exactly what it says :) My battery doesn't seem do be hurting noticeably from it though and for me the hit in "overall performance" is worth it for the sake of multitasking. Maybe someone else will think the same as I do. Anyway, thanks for merging the PR.

**Pull request merged**
